[package]
name = "green-vita-transport-tests"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
sctp = { package = "rtc-sctp", version = "=0.20.0-rc.2" }
shared = { package = "rtc-shared", version = "=0.20.0-rc.2", default-features = false }
bytes = "1"
rtc = { path = "../../vendor/rtc" }
